
import { ChiTieu } from './types';

export const CHI_TIEU_DATA: ChiTieu[] = [
    { stt: '1', chiTieu: 'Tổng sản phẩm trên địa bàn (GRDP) (giá so sánh 2010)', donVi: 'Cục Thống kê', ky: 'Quý' },
    { stt: '1*', chiTieu: 'GRDP - Nông, lâm nghiệp, thuỷ sản', donVi: 'Cục Thống kê', ky: 'Quý' },
    { stt: '1*', chiTieu: 'GRDP - Công nghiệp và xây dựng', donVi: 'Cục Thống kê', ky: 'Quý' },
    { stt: '1*', chiTieu: 'GRDP - Dịch vụ', donVi: 'Cục Thống kê', ky: 'Quý' },
    { stt: '5', chiTieu: 'Tổng sản phẩm trên địa bàn bình quân đầu người', donVi: 'Cục Thống kê', ky: 'Năm' },
    { stt: '6', chiTieu: 'Tỷ trọng đóng góp của năng suất các nhân tố tổng hợp (TFP)', donVi: 'Sở Khoa học và Công nghệ', ky: 'Năm' },
    { stt: 'I', chiTieu: 'TỔNG THU NSNN TRÊN ĐỊA BÀN', donVi: 'Sở Tài chính', ky: 'Tháng' },
    { stt: 'I.1', chiTieu: 'Thu nội địa', donVi: 'Sở Tài chính', ky: 'Tháng' },
    { stt: 'I.1*', chiTieu: 'Thu từ doanh nghiệp nhà nước', donVi: 'Sở Tài chính', ky: 'Tháng' },
    { stt: 'I.1*', chiTieu: 'Thu từ doanh nghiệp đầu tư nước ngoài', donVi: 'Sở Tài chính', ky: 'Tháng' },
    { stt: 'I.1*', chiTieu: 'Thu thuế thu nhập cá nhân', donVi: 'Sở Tài chính', ky: 'Tháng' },
    { stt: 'I.1*', chiTieu: 'Tiền sử dụng đất', donVi: 'Sở Tài chính', ky: 'Tháng' },
    { stt: 'II', chiTieu: 'TỔNG CHI NGÂN SÁCH NHÀ NƯỚC', donVi: 'Sở Tài chính', ky: 'Tháng' },
    { stt: 'II.1', chiTieu: 'Chi đầu tư phát triển', donVi: 'Sở Tài chính', ky: 'Tháng' },
    { stt: 'II.3', chiTieu: 'Chi thường xuyên', donVi: 'Sở Tài chính', ky: 'Tháng' },
    { stt: 'I.1', chiTieu: 'Chỉ số sản xuất công nghiệp', donVi: 'Cục Thống kê', ky: 'Tháng' },
    { stt: 'II.1', chiTieu: 'Tổng mức bán lẻ hàng hoá và doanh thu dịch vụ tiêu dùng', donVi: 'Cục Thống kê', ky: 'Tháng' },
    { stt: 'II.2', chiTieu: 'Doanh thu du lịch', donVi: 'Sở Du lịch', ky: 'Tháng' },
    { stt: 'II.3', chiTieu: 'Khách lưu trú', donVi: 'Sở Du lịch', ky: 'Tháng' },
    { stt: 'II.3*', chiTieu: 'Khách lưu trú - Khách quốc tế', donVi: 'Sở Du lịch', ky: 'Tháng' },
    { stt: 'III.1', chiTieu: 'Kim ngạch xuất khẩu hàng hóa trên địa bàn', donVi: 'Cục Thống kê', ky: 'Tháng' },
    { stt: 'IV.1', chiTieu: 'Số xã được công nhận đạt chuẩn nông thôn mới', donVi: 'Sở Nông nghiệp và PTNT', ky: 'Năm' },
    { stt: '1', chiTieu: 'Số ca mắc mới sốt xuất huyết', donVi: 'Sở Y tế', ky: 'Tháng' },
    { stt: '1', chiTieu: 'Số ca mắc mới tay chân miệng', donVi: 'Sở Y tế', ky: 'Tháng' },
    { stt: '2', chiTieu: 'Ngộ độc thực phẩm (Số vụ)', donVi: 'Sở Y tế', ky: 'Tháng' },
    { stt: '5', chiTieu: 'Số bác sĩ trên 10.000 dân', donVi: 'Sở Y tế', ky: 'Quý' },
    { stt: '2', chiTieu: 'Số lao động có việc làm trong nền kinh tế', donVi: 'Cục Thống kê', ky: 'Quý' },
    { stt: '3', chiTieu: 'Tỷ lệ lao động đã qua đào tạo', donVi: 'Sở Lao động - Thương binh và Xã hội', ky: 'Quý' },
    { stt: '4', chiTieu: 'Số người lao động có việc làm tăng thêm', donVi: 'Sở Lao động - Thương binh và Xã hội', ky: 'Năm' },
    { stt: '2', chiTieu: 'Số hộ nghèo', donVi: 'Sở Lao động - Thương binh và Xã hội; UBND các huyện, thị xã, thành phố', ky: '6 tháng' },
    { stt: '2', chiTieu: 'Tỷ lệ hộ nghèo', donVi: 'Sở Lao động - Thương binh và Xã hội; UBND các huyện, thị xã, thành phố', ky: '6 tháng' },
    { stt: 'I.3', chiTieu: 'Lũy kế số vốn đã giải ngân từ đầu năm đến kỳ báo cáo (Đầu tư công)', donVi: 'Sở Kế hoạch và Đầu tư', ky: 'Tháng' },
    { stt: 'II.1', chiTieu: 'Số dự án và vốn đầu tư đăng ký (Ngoài ngân sách)', donVi: 'Sở Kế hoạch và Đầu tư', ky: 'Tháng' },
    { stt: 'II.2', chiTieu: 'Số dự án và vốn đầu tư nước ngoài đăng ký (FDI)', donVi: 'Sở Kế hoạch và Đầu tư', ky: 'Tháng' },
    { stt: 'II.3', chiTieu: 'Tổng vốn đầu tư phát triển toàn xã hội', donVi: 'Sở Kế hoạch và Đầu tư', ky: '9 tháng' },
    { stt: '1', chiTieu: 'Tổng số doanh nghiệp đăng ký thành lập', donVi: 'Sở Kế hoạch và Đầu tư', ky: 'Tháng' },
    { stt: '4', chiTieu: 'Số doanh nghiệp quay trở lại hoạt động', donVi: 'Sở Kế hoạch và Đầu tư', ky: 'Tháng' },
    { stt: '6', chiTieu: 'Số doanh nghiệp giải thể', donVi: 'Sở Kế hoạch và Đầu tư', ky: 'Tháng' },
    { stt: '7', chiTieu: 'Lũy kế doanh nghiệp đang hoạt động đến kỳ báo cáo', donVi: 'Cục Thuế tỉnh', ky: 'Tháng' },
    { stt: 'I.1', chiTieu: 'Phạm tội về trật tự xã hội (Số vụ)', donVi: 'Công an tỉnh', ky: 'Tháng' },
    { stt: 'II.1', chiTieu: 'Số vụ tai nạn giao thông', donVi: 'Công an tỉnh', ky: 'Tháng' },
    { stt: 'III.1', chiTieu: 'Số vụ cháy, nổ', donVi: 'Công an tỉnh', ky: 'Tháng' },
    { stt: '1', chiTieu: 'Chỉ số Cải cách hành chính (PAR INDEX)', donVi: 'Sở Nội vụ', ky: 'Năm' },
    { stt: '6', chiTieu: 'Chỉ số Năng lực cạnh tranh (PCI)', donVi: 'Sở Kế hoạch và Đầu tư', ky: 'Năm' },
    { stt: '8', chiTieu: 'Chỉ số Chuyển đổi số (DTI)', donVi: 'Sở Thông tin và Truyền thông', ky: 'Năm' },
    { stt: 'II', chiTieu: 'Kết quả giải quyết thủ tục hành chính', donVi: 'Tích hợp số liệu Hệ thống thông tin giải quyết thủ tục hành chính tỉnh Khánh Hòa', ky: 'Tháng' },
    { stt: 'IV', chiTieu: 'Kết quả thực hiện nhiệm vụ của UBND tỉnh, Chủ tịch UBND tỉnh giao', donVi: 'Tích hợp số liệu Phần mềm nhắc việc của UBND tỉnh', ky: 'Tháng' },
];
